apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: deepatp/pythonrepo:1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: arpithajayanthi/k8s:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
